### ISSUE TITLE
Don't check Pender connectivity by submitting a link

### ISSUE THREAD

**Issue by infojunkie** [amoedoamorim/penderclient#4]
You are checking connectivity to Pender by submitting a hard-coded link. This works but it is a) wasteful in resources (Pender does extra work and stores extra data), and b) error-prone (this link may disappear from the Web in the future). A better approach would be to use HTTP verbs HEAD or OPTIONS to check connectivity. If Pender does not respond to those verbs, we can work to submit a PR there.

**Comment by infojunkie** [comment]
According to the RFC, HEAD is the right choice: https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.4

**Comment by amoedoamorim** [comment]
Seems like for HTTP methods HEAD or OPTIONS the API won't return the Access-Control-Allow-Origin header, resulting in a blocked Cross-Origin Request.

**Comment by infojunkie** [comment]
Yes, that's expected. If you're ready to dive into backend work, you can fork Pender https://github.com/meedan/pender to add HEAD support to the single `/medias` endpoint.
